# Generated by Django 4.2.2 on 2023-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('adress', models.CharField(max_length=200)),
                ('working', models.BooleanField(default=True)),
                ('depertment', models.CharField(max_length=50)),
            ],
        ),
    ]
